# -*- Mode: Python; tab-width: 4 -*-
# $Id: mime_type_table.py,v 1.1 1995/10/25 03:37:03 rushing Exp $

# built-in mapping of filename extensions to mime types
# this list was taken from Apache 0.6.2, is probably verbatim
# from NCSA httpd 1.3.

content_type_map = \
 {
	 '':		'text/plain',
	 'bin':		'application/octet-stream',
	 'oda':		'application/oda',
	 'pdf':		'application/pdf',
	 'ai':		'application/postscript',
	 'eps':		'application/postscript',
	 'ps':		'application/postscript',
	 'rtf':		'application/rtf',
	 'mif':		'application/x-mif',
	 'csh':		'application/x-csh',
	 'dvi':		'application/x-dvi',
	 'hdf':		'application/x-hdf',
	 'latex':	'application/x-latex',
	 'nc':		'application/x-netcdf',
	 'cdf':		'application/x-netcdf',
	 'sh':		'application/x-sh',
	 'tcl':		'application/x-tcl',
	 'tex':		'application/x-tex',
	 'texinfo':	'application/x-texinfo',
	 'texi':	'application/x-texinfo',
	 't':		'application/x-troff',
	 'tr':		'application/x-troff',
	 'roff':	'application/x-troff',
	 'man':		'application/x-troff-man',
	 'me':		'application/x-troff-me',
	 'ms':		'application/x-troff-ms',
	 'src':		'application/x-wais-source',
	 'zip':		'application/zip',
	 'bcpio':	'application/x-bcpio',
	 'cpio':	'application/x-cpio',
	 'gtar':	'application/x-gtar',
	 'shar':	'application/x-shar',
	 'sv4cpio':	'application/x-sv4cpio',
	 'sv4crc':	'application/x-sv4crc',
	 'tar':		'application/x-tar',
	 'ustar':	'application/x-ustar',
	 'au':		'audio/basic',
	 'snd':		'audio/basic',
	 'aif':		'audio/x-aiff',
	 'aiff':	'audio/x-aiff',
	 'aifc':	'audio/x-aiff',
	 'wav':		'audio/x-wav',
	 'gif':		'image/gif',
	 'ief':		'image/ief',
	 'jpeg':	'image/jpeg',
	 'jpg':		'image/jpeg',
	 'jpe':		'image/jpeg',
	 'tiff':	'image/tiff',
	 'tif':		'image/tiff',
	 'ras':		'image/x-cmu-raster',
	 'pnm':		'image/x-portable-anymap',
	 'pbm':		'image/x-portable-bitmap',
	 'pgm':		'image/x-portable-graymap',
	 'ppm':		'image/x-portable-pixmap',
	 'rgb':		'image/x-rgb',
	 'xbm':		'image/x-xbitmap',
	 'xpm':		'image/x-xpixmap',
	 'xwd':		'image/x-xwindowdump',
	 'htm':		'text/html',
	 'html':	'text/html',
	 'txt':		'text/plain',
	 'rtx':		'text/richtext',
	 'tsv':		'text/tab-separated-values',
	 'etx':		'text/x-setext',
	 'mpeg':	'video/mpeg',
	 'mpg':		'video/mpeg',
	 'mpe':		'video/mpeg',
	 'qt':		'video/quicktime',
	 'mov':		'video/quicktime',
	 'avi':		'video/x-msvideo',
	 'movie':	'video/x-sgi-movie',
	 }

